// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	upload "lc/netdisk/internal/handler/upload"
	"lc/netdisk/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/check_file",
				Handler: upload.CheckFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: upload.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/check_chunk",
				Handler: upload.CheckChunkHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chunk",
				Handler: upload.UploadChunkHandler(serverCtx),
			},
		},
		rest.WithPrefix("/file/upload"),
	)
}
