// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Password string `json:"password"`
}

type RegisterReq struct {
}

type CheckFileReq struct {
	FolderId int64  `json:"folderId"`
	Hash     string `json:"hash"`
	Size     int64  `json:"size"`
	Name     string `json:"name"`
	Ext      string `json:"ext"`
}

type UploadReq struct {
	FileNetdiskId int64 `json:"fileNetdiskId"`
}

type CheckChunkReq struct {
	Hash     string `json:"hash"`
	ChunkSeq int64  `json:"chunkSeq"`
}

type UploadChunkReq struct {
	FileId int64 `json:"fileId"`
}

type CheckFileResp struct {
	FileId int64 `json:"fileId"`
	Status int8  `json:"status"` // 0：文件未上传，1：文件已存在
}

type ListFileReq struct {
	FolderId int64 `path:"folderId"`
}

type UpdateFileReq struct {
	FileId int64  `json:"fileId"`
	Name   string `json:"name"`
}

type DeleteBatchReq struct {
	FolderIds []int64 `json:"folderIds"`
	FileIds   []int64 `json:"fileIds"`
}

type DeleteBatchTrulyReq struct {
	FolderIds []int64 `json:"folderIds"`
	FileIds   []int64 `json:"fileIds"`
}

type ListFileFolderReq struct {
	ParentFolderId int64 `path:"parentFolderId"`
}

type CreateFolderReq struct {
	Name           string `json:"name"`
	ParentFolderId int64  `json:"parentFolderId"`
}

type UpdateFolderReq struct {
	FolderId int64  `json:"folderId"`
	Name     string `json:"name"`
}

type MoveReq struct {
	ParentFolderId int64   `json:"parentFolderId"`
	FolderIds      []int64 `json:"folderIds"`
	FileIds        []int64 `json:"fileIds"`
}

type DeleteBatchResp struct {
	FolderIds []int64 `json:"folderIds"`
	FileIds   []int64 `json:"fileIds"`
}

type ListDeletedItemsResp struct {
	Folders []*ListDeletedFolderStruct `json:"folders"`
	Files   []*ListDeletedFileStruct   `json:"files"`
}

type DeleteBatchTrulyResp struct {
	FolderIds []int64 `json:"folderIds"`
	FileIds   []int64 `json:"fileIds"`
}

type ListFileFolderResp struct {
	Folders []*ListFolderStruct `json:"folders"`
	Files   []*ListFileStruct   `json:"files"`
}

type ListFolderStruct struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type ListFileStruct struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Url    string `json:"url"`
	Status int8   `json:"status"`
}

type ListDeletedFolderStruct struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	DelTime int64  `json:"delTime"`
}

type ListDeletedFileStruct struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Url     string `json:"url"`
	DelTime int64  `json:"delTime"`
}

type CheckSizeReq struct {
	FileId int64 `json:"fileId"`
}

type DownloadReq struct {
	FileId int64 `json:"fileId"`
}

type ChunkDownloadReq struct {
	FileId   int64 `json:"fileId"`
	ChunkSeq int64 `json:"chunkSeq"`
}

type CheckSizeResp struct {
	IsBig    int8  `json:"status"`
	ChunkNum int64 `json:"chunkNum"`
}

type UpdateUserDetailReq struct {
}

type GetUserDetailReq struct {
	UserId int64 `path:"userId"`
}

type UpdateAvatarReq struct {
}
