// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterReq struct {
	Username       string `json:"username"`
	Password       string `json:"password"`
	PasswordRepeat string `json:"passwordRepeat"`
}

type LoginResp struct {
	Token    string   `json:"token"`
	UserInfo UserInfo `json:"userInfo"`
}

type UserInfo struct {
	UserId    int64  `json:"userId"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Email     string `json:"email"`
	Signature string `json:"signature"`
	Status    int8   `json:"status"`
}

type CheckFileReq struct {
	FolderId int64  `json:"folderId"`
	Hash     string `json:"hash"`
	Size     int64  `json:"size"`
	Name     string `json:"name"`
	Ext      string `json:"ext"`
}

type UploadReq struct {
	FileId int64 `json:"fileId"`
}

type CheckChunkReq struct {
	Hash     string `json:"hash"`
	ChunkSeq int64  `json:"chunkSeq"`
}

type UploadChunkReq struct {
	FileId int64 `json:"fileId"`
}

type CheckFileResp struct {
	FileId int64 `json:"fileId"`
	Status int8  `json:"status"` // 0：文件未上传，1：文件已存在
}

type ListFileReq struct {
	FolderId int64 `path:"folderId"`
}

type UpdateFileReq struct {
	FileId int64  `json:"fileId"`
	Name   string `json:"name"`
}

type CopyFilesReq struct {
	ParentFolderId int64 `path:"parentFolderId"`
	FileIdsStruct
}

type DeleteBatchReq struct {
	FolderIdsStruct
	FileIdsStruct
}

type RecoverReq struct {
	FolderIdsStruct
	FileIdsStruct
}

type DeleteBatchTrulyReq struct {
	FolderIdsStruct
	FileIdsStruct
}

type ParentFolderIdReq struct {
	ParentFolderId int64 `path:"parentFolderId"`
}

type CreateFolderReq struct {
	Name           string `json:"name"`
	ParentFolderId int64  `json:"parentFolderId"`
}

type UpdateFolderReq struct {
	FolderId int64  `json:"folderId"`
	Name     string `json:"name"`
}

type CopyFoldersReq struct {
	ParentFolderId int64 `path:"parentFolderId"`
	FolderIdsStruct
}

type MoveFilesReq struct {
	ParentFolderId int64 `json:"parentFolderId"`
	FileIdsStruct
}

type MoveFoldersReq struct {
	ParentFolderId int64 `json:"parentFolderId"`
	FolderIdsStruct
}

type ListDeletedItemsResp struct {
	Folders []*ListDeletedFolderStruct `json:"folders"`
	Files   []*ListDeletedFileStruct   `json:"files"`
}

type ListFileFolderResp struct {
	Folders []*ListFolderStruct `json:"folders"`
	Files   []*ListFileStruct   `json:"files"`
}

type ListFolderStruct struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Updated string `json:"updated,omitempty"`
}

type ListFileStruct struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Url     string `json:"url"`
	Status  int8   `json:"status"`
	Size    int64  `json:"size"`
	Updated string `json:"updated"`
}

type ListDeletedFolderStruct struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	DelTime int64  `json:"delTime"`
}

type ListDeletedFileStruct struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Url     string `json:"url"`
	DelTime int64  `json:"delTime"`
}

type FolderIdsStruct struct {
	FolderIds []int64 `json:"folderIds"`
}

type FileIdsStruct struct {
	FileIds []int64 `json:"fileIds"`
}

type CheckSizeReq struct {
	FileId int64 `json:"fileId"`
}

type DownloadReq struct {
	FileId int64 `json:"fileId"`
}

type ChunkDownloadReq struct {
	FileId   int64 `json:"fileId"`
	ChunkSeq int64 `json:"chunkSeq"`
}

type CheckSizeResp struct {
	IsBig    int8  `json:"status"`
	ChunkNum int64 `json:"chunkNum"`
}

type UpdateUserDetailReq struct {
}

type GetUserDetailReq struct {
	UserId int64 `path:"userId"`
}

type UpdateAvatarReq struct {
}
